development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: curry
  pool: 5
  username: sitedev
  password: "112233aabbcc"
  host: 210.30.96.32
  port: 3306

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: curry
  pool: 5
  username: sitedev
  password: "112233aabbcc"
  host: 210.30.96.32
  port: 3306
